# Site settings
title: My Personal Blog & Website
subtitle: by Frank FitzGerald
email: me@frankfitzgerald.net
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://frankfitzgerald.github.io" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Orlando
state: FL
zip_code: 327**
country: United States of America
phone: (407) 708-8813

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/FrankFitzGerald
gitlab_url: https://gitlab.com/FrankFitzGerald
googleplus_url:
instagram_url: https://instagram.com/frankjfitzgerald
linkedin_url: https://www.linkedin.com/in/fitzgeraldfrank
pinterest_url:
slack_url:
twitter_url: https://twitter.com/Frank_Fitz

# Build settings
markdown: kramdown
